#!/bin/dash
wget -c -O /tmp/hosts.txt http://www.mvps.org/winhelp2002/hosts.txt
sed -i -e 's:127.0.0.1:0.0.0.0:g' -e "s:^.*localhost.$:127.0.0.1 localhost `hostname`:" /tmp/hosts.txt
cat /tmp/hosts.txt | tr -d "\r" > /etc/hosts
rm /tmp/hosts.txt
